# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: gfasales-pipeline
  path.config: "/usr/share/logstash/pipeline/gfasales.conf"

- pipeline.id: gfasales_incremental-pipeline
  path.config: "/usr/share/logstash/pipeline/gfasales_incremental.conf"